root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Команда для сборки бинарника в tmp/main
  cmd = "swag init -g cmd/main.go && go build -o tmp/main cmd/main.go"
  bin = "./tmp/main"  # Указываем путь к бинарному файлу
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "3s"  # Увеличиваем задержку
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = ["kill $(lsof -t -i:3000)"]  # Завершаем процесс на порту 3000
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
